version: 1
policies:
  - id: cf-autotick-bot-test-package-policy
    repo: cf-autotick-bot-test-package-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: conda-smithy-feedstock-policy
    repo: conda-smithy-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: conda-forge-ci-setup-feedstock-policy
    repo: conda-forge-ci-setup-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: libmagma-feedstock-policy
    repo: libmagma-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: pytorch-cpu-feedstock-policy
    repo: pytorch-cpu-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: cutlass-feedstock-policy
    repo: cutlass-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: tensorflow-feedstock-policy
    repo: tensorflow-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: mongodb-feedstock-policy
    repo: mongodb-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: jaxlib-feedstock-policy
    repo: jaxlib-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: cirun-py-policy
    repo: cirun-py
    teams:
      - team1
      - team2
      - team3
    roles:
      - role1
      - role2
      - role3
    users:
      - user1
      - user2
      - user3
    pull_request: false
    users_from_json: https://cirun.io/users.json
access_control:
  - resource: cirun-openstack-gpu-large
    policies:
      - cf-autotick-bot-test-package-policy
      - conda-smithy-feedstock-policy
      - conda-forge-ci-setup-feedstock-policy
      - libmagma-feedstock-policy
      - pytorch-cpu-feedstock-policy
  - resource: cirun-openstack-gpu-xlarge
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-medium
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-large
    policies:
      - cf-autotick-bot-test-package-policy
      - pytorch-cpu-feedstock-policy
      - cutlass-feedstock-policy
      - tensorflow-feedstock-policy
      - mongodb-feedstock-policy
      - jaxlib-feedstock-policy
  - resource: cirun-openstack-gpu-2xlarge
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-gpu-4xlarge
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-2xlarge
    policies:
      - cf-autotick-bot-test-package-policy
      - jaxlib-feedstock-policy
  - resource: cirun-openstack-cpu-4xlarge
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-xlarge
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-runner-1
    policies:
      - cirun-py-policy
