# Self-Hosted Github Action Runners on Openstack via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: cirun-openstack-gpu-large
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: gpu_large
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-nvidia-20230914
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-gpu-large

  - name: cirun-openstack-gpu-xlarge
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: gpu_xlarge
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-nvidia-20230914
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-gpu-xlarge

  - name: cirun-openstack-cpu-medium
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: ci_medium
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-20231018
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-cpu-medium

  - name: cirun-openstack-cpu-large
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: ci_large
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-20231018
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-cpu-large

  - name: cirun-macos-runner
    cloud: on_prem
    instance_type: 4vcpu-4gb-40gb
    machine_image: "macos-sequoia-vanilla:latest"
    region: RegionOne
    labels:
      - cirun-macos-runner
